export const MODULE_MASTER = {
    ORGANIZATIONS: 1,
    COMPANIES: 2,
    ENTITIES: 3,
    ADDRESS: 4,
    ITEMS: 5,
    DEVICES: 8,
    CONTACTS: 9
};  

export const ADDRESS_TYPES = {
    PHONE: 1,
    EMAIL: 2,
    FAX: 3
};

export const MESSAGE_TEMPLATE_VARIABLES = [
    'ORGANIZATION NAME',
    'COMPANY NAME',
    'ENTITY NAME',
    'ENTITY FIRSTNAME',
    'ENTITY LASTNAME',
    'ENTITY TYPE',
    'ENTITY ADDRESS ITEM',
    'ITEM NAME',
    'ITEM TYPE',
    'DEVICE NAME',
    'DEVICE TYPE',
    'DEVICE BRAND',
    'DEVICE MODEL',
    'DEVICE MONITOR STATUS',
    'DEVICE MONITOR NAME',
    'DEVICE MONITOR FREQUENCY',
    'DEVICE MONITOR TIME UNIT',
    'DEVICE PARAMETERS',
    'DEVICE PARAMETER VALUES',
]